
import React, { useState, useMemo } from 'react';
import { Task, TaskStatus, TaskPriority } from '../types';
import { CheckIcon } from './icons/CheckIcon';
import { TrashIcon } from './icons/TrashIcon';
import { EditIcon } from './icons/EditIcon';
import { XIcon } from './icons/XIcon';
import { CalendarIcon } from './icons/CalendarIcon';
import { SARS_DEADLINES, getCipcDeadline } from '../utils/taxDates';

interface CalendarViewProps {
    tasks: Task[];
    onAddTask: (task: Omit<Task, 'id'>) => void;
    onUpdateTask: (task: Task) => void;
    onDeleteTask: (taskId: string) => void;
}

const CalendarView: React.FC<CalendarViewProps> = ({ tasks, onAddTask, onUpdateTask, onDeleteTask }) => {
    const [isAdding, setIsAdding] = useState(false);
    const [editingTask, setEditingTask] = useState<Task | null>(null);
    const [currentDate, setCurrentDate] = useState(new Date());
    const [selectedDate, setSelectedDate] = useState<string>(new Date().toISOString().split('T')[0]);
    const [isSyncing, setIsSyncing] = useState(false);
    
    const [newTask, setNewTask] = useState<Partial<Task>>({
        title: '',
        description: '',
        dueDate: new Date().toISOString().split('T')[0],
        status: 'todo',
        priority: 'medium'
    });

    // Calendar Grid Logic
    const daysInMonth = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0).getDate();
    const firstDayOfMonth = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1).getDay();
    
    const monthName = currentDate.toLocaleString('default', { month: 'long' });
    const year = currentDate.getFullYear();

    const days = useMemo(() => {
        const dayArray = [];
        // Empty slots for days before the first of the month
        for (let i = 0; i < firstDayOfMonth; i++) {
            dayArray.push(null);
        }
        // Actual days
        for (let i = 1; i <= daysInMonth; i++) {
            dayArray.push(i);
        }
        return dayArray;
    }, [currentDate, daysInMonth, firstDayOfMonth]);

    const prevMonth = () => {
        setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1));
    };

    const nextMonth = () => {
        setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1));
    };

    const getTasksForDate = (day: number) => {
        const dateStr = `${year}-${String(currentDate.getMonth() + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        return tasks.filter(t => t.dueDate === dateStr);
    };

    const handleDateClick = (day: number) => {
        const dateStr = `${year}-${String(currentDate.getMonth() + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        setSelectedDate(dateStr);
        setNewTask(prev => ({ ...prev, dueDate: dateStr }));
    };

    // Google Calendar Deep Link Generator
    const addToGoogleCalendar = (task: Task) => {
        const start = task.dueDate.replace(/-/g, '') + 'T090000Z';
        const end = task.dueDate.replace(/-/g, '') + 'T100000Z'; // 1 hour default duration
        const details = task.description || 'Generated by SA Bookkeeper AI';
        const url = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(task.title)}&dates=${start}/${end}&details=${encodeURIComponent(details)}`;
        window.open(url, '_blank');
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (editingTask) {
            onUpdateTask({ ...editingTask, ...newTask } as Task);
            setEditingTask(null);
        } else {
            if (newTask.title && newTask.dueDate) {
                onAddTask({
                    title: newTask.title,
                    description: newTask.description || '',
                    dueDate: newTask.dueDate,
                    status: newTask.status as TaskStatus || 'todo',
                    priority: newTask.priority as TaskPriority || 'medium'
                });
            }
        }
        setIsAdding(false);
        // Reset form but keep date
        setNewTask({
            title: '',
            description: '',
            dueDate: selectedDate,
            status: 'todo',
            priority: 'medium'
        });
    };

    const startEditing = (task: Task) => {
        setEditingTask(task);
        setNewTask(task);
        setIsAdding(true);
    };

    const handlePopulateTaxDates = () => {
        if (!window.confirm("This will add standard SARS tax deadlines (Provisional, EMP501, etc.) to your calendar for the current year. Continue?")) {
            return;
        }
        
        setIsSyncing(true);
        const currentYear = new Date().getFullYear();

        // 1. Add SARS Deadlines
        SARS_DEADLINES.forEach(deadline => {
            const dateStr = `${currentYear}-${String(deadline.month).padStart(2, '0')}-${String(deadline.day).padStart(2, '0')}`;
            
            // Basic duplicate check (only checks title and date locally for now)
            const exists = tasks.some(t => t.title === deadline.title && t.dueDate === dateStr);
            
            if (!exists) {
                onAddTask({
                    title: deadline.title,
                    description: deadline.description,
                    dueDate: dateStr,
                    status: 'todo',
                    priority: deadline.priority
                });
            }
        });

        // 2. Ask for CIPC Anniversary
        const anniversary = window.prompt("To add your CIPC Annual Return deadline, please enter your Company Registration Date (YYYY-MM-DD):", `${currentYear}-01-01`);
        
        if (anniversary) {
            // Parse user input to get month/day, but apply to current year for the due date
            const inputDate = new Date(anniversary);
            if (!isNaN(inputDate.getTime())) {
                // Set anniversary to current year to calculate this year's deadline
                const thisYearAnniversary = new Date(currentYear, inputDate.getMonth(), inputDate.getDate());
                const dueDateStr = getCipcDeadline(thisYearAnniversary.toISOString());
                
                const cipcTitle = "CIPC Annual Return Due";
                const exists = tasks.some(t => t.title === cipcTitle && t.dueDate === dueDateStr);

                if (!exists) {
                    onAddTask({
                        title: cipcTitle,
                        description: "Annual Return must be filed with CIPC within 30 business days of company anniversary.",
                        dueDate: dueDateStr,
                        status: 'todo',
                        priority: 'high'
                    });
                }
            } else {
                alert("Invalid date format. CIPC deadline skipped.");
            }
        }

        setIsSyncing(false);
    };

    const getPriorityColor = (priority: string) => {
        switch(priority) {
            case 'high': return 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300';
            case 'medium': return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300';
            case 'low': return 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300';
            default: return 'bg-slate-100 text-slate-800';
        }
    };

    const selectedTasks = tasks.filter(t => t.dueDate === selectedDate);

    return (
        <div className="h-full flex flex-col lg:flex-row gap-6 animate-fade-in">
            
            {/* Left: Calendar Grid */}
            <div className="flex-grow bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm p-6">
                <div className="flex flex-col sm:flex-row justify-between items-center mb-6 gap-4">
                    <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                        <CalendarIcon className="w-6 h-6 text-teal-600 dark:text-teal-400" />
                        {monthName} {year}
                    </h2>
                    <div className="flex items-center gap-3">
                        <button 
                            onClick={handlePopulateTaxDates}
                            disabled={isSyncing}
                            className="text-xs font-medium bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 px-3 py-2 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors flex items-center gap-2"
                        >
                            {isSyncing ? 'Syncing...' : 'Import SARS/CIPC Dates'}
                        </button>
                        <div className="flex gap-1 bg-slate-100 dark:bg-slate-800 rounded-lg p-1">
                            <button onClick={prevMonth} className="p-1.5 hover:bg-white dark:hover:bg-slate-700 rounded shadow-sm text-slate-600 dark:text-slate-300">&lt;</button>
                            <button onClick={nextMonth} className="p-1.5 hover:bg-white dark:hover:bg-slate-700 rounded shadow-sm text-slate-600 dark:text-slate-300">&gt;</button>
                        </div>
                    </div>
                </div>

                <div className="grid grid-cols-7 gap-2 mb-2">
                    {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(d => (
                        <div key={d} className="text-center text-sm font-semibold text-slate-500 dark:text-slate-400 py-2">{d}</div>
                    ))}
                </div>
                
                <div className="grid grid-cols-7 gap-2">
                    {days.map((day, idx) => {
                        if (day === null) return <div key={`empty-${idx}`} className="h-24 bg-slate-50/50 dark:bg-slate-900/50 rounded-lg"></div>;
                        
                        const dayTasks = getTasksForDate(day);
                        const isSelected = `${year}-${String(currentDate.getMonth() + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}` === selectedDate;
                        
                        return (
                            <div 
                                key={day} 
                                onClick={() => handleDateClick(day)}
                                className={`h-24 p-2 rounded-lg border cursor-pointer transition-all overflow-hidden hover:shadow-md ${
                                    isSelected 
                                    ? 'border-teal-500 bg-teal-50 dark:bg-teal-900/20' 
                                    : 'border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 hover:border-teal-300'
                                }`}
                            >
                                <div className="flex justify-between items-start mb-1">
                                    <span className={`text-sm font-semibold ${isSelected ? 'text-teal-700 dark:text-teal-300' : 'text-slate-700 dark:text-slate-300'}`}>{day}</span>
                                    {dayTasks.length > 0 && (
                                        <span className="bg-teal-100 text-teal-800 text-xs px-1.5 rounded-full dark:bg-teal-900 dark:text-teal-200">{dayTasks.length}</span>
                                    )}
                                </div>
                                <div className="space-y-1">
                                    {dayTasks.slice(0, 2).map(task => (
                                        <div key={task.id} className={`text-[10px] truncate px-1 rounded border-l-2 ${
                                            task.title.includes('SARS') || task.title.includes('Tax') ? 'border-red-400' : 'border-transparent'
                                        } ${task.status === 'done' ? 'line-through text-slate-400' : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'}`}>
                                            {task.title}
                                        </div>
                                    ))}
                                    {dayTasks.length > 2 && (
                                        <div className="text-xs text-slate-400 text-center">+{dayTasks.length - 2} more</div>
                                    )}
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>

            {/* Right: Task List & Add Form */}
            <div className="w-full lg:w-96 flex flex-col gap-6">
                
                {/* Header & Add Button */}
                <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm p-6">
                    <div className="flex justify-between items-center mb-4">
                        <div>
                            <h3 className="text-lg font-bold text-slate-900 dark:text-white">Tasks</h3>
                            <p className="text-sm text-slate-500 dark:text-slate-400">{new Date(selectedDate).toDateString()}</p>
                        </div>
                        <button 
                            onClick={() => setIsAdding(true)}
                            className="bg-teal-600 text-white p-2 rounded-full hover:bg-teal-500 transition-colors shadow-sm"
                        >
                            <span className="text-xl font-bold leading-none">+</span>
                        </button>
                    </div>

                    {/* Task List for Selected Day */}
                    <div className="space-y-3 max-h-[400px] overflow-y-auto pr-1">
                        {selectedTasks.length === 0 ? (
                            <p className="text-center text-slate-500 dark:text-slate-400 py-8 italic">No tasks for this day.</p>
                        ) : (
                            selectedTasks.map(task => (
                                <div key={task.id} className={`p-3 rounded-lg border transition-all group ${task.status === 'done' ? 'bg-slate-50 border-slate-200 dark:bg-slate-900/50 dark:border-slate-800 opacity-75' : 'bg-white border-slate-200 dark:bg-slate-800 dark:border-slate-700'}`}>
                                    <div className="flex items-start justify-between gap-2">
                                        <div className="flex items-start gap-3">
                                            <button 
                                                onClick={() => onUpdateTask({ ...task, status: task.status === 'done' ? 'todo' : 'done' })}
                                                className={`mt-1 w-5 h-5 rounded border flex items-center justify-center transition-colors ${task.status === 'done' ? 'bg-teal-500 border-teal-500 text-white' : 'border-slate-300 dark:border-slate-600 hover:border-teal-500'}`}
                                            >
                                                {task.status === 'done' && <CheckIcon className="w-3 h-3" />}
                                            </button>
                                            <div>
                                                <h4 className={`text-sm font-semibold ${task.status === 'done' ? 'line-through text-slate-500 dark:text-slate-500' : 'text-slate-800 dark:text-white'}`}>{task.title}</h4>
                                                {task.description && <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">{task.description}</p>}
                                                <div className="flex gap-2 mt-2">
                                                    <span className={`text-[10px] uppercase font-bold px-1.5 py-0.5 rounded ${getPriorityColor(task.priority)}`}>{task.priority}</span>
                                                    <button onClick={() => addToGoogleCalendar(task)} className="text-[10px] text-blue-600 dark:text-blue-400 hover:underline flex items-center gap-1">
                                                        Add to G-Cal ↗
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="flex flex-col gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                            <button onClick={() => startEditing(task)} className="text-slate-400 hover:text-teal-500"><EditIcon className="w-4 h-4" /></button>
                                            <button onClick={() => onDeleteTask(task.id)} className="text-slate-400 hover:text-red-500"><TrashIcon className="w-4 h-4" /></button>
                                        </div>
                                    </div>
                                </div>
                            ))
                        )}
                    </div>
                </div>

                {/* Add/Edit Modal (Inline Overlay) */}
                {isAdding && (
                    <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50 p-4">
                        <div className="bg-white dark:bg-slate-900 rounded-xl shadow-xl w-full max-w-md p-6" onClick={e => e.stopPropagation()}>
                            <div className="flex justify-between items-center mb-4">
                                <h3 className="text-lg font-bold text-slate-800 dark:text-white">{editingTask ? 'Edit Task' : 'New Task'}</h3>
                                <button onClick={() => { setIsAdding(false); setEditingTask(null); }} className="text-slate-400 hover:text-slate-600">
                                    <XIcon className="w-5 h-5" />
                                </button>
                            </div>
                            <form onSubmit={handleSubmit} className="space-y-4">
                                <input 
                                    required
                                    placeholder="Task Title"
                                    className="w-full p-2 rounded border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 dark:text-white"
                                    value={newTask.title}
                                    onChange={e => setNewTask({...newTask, title: e.target.value})}
                                />
                                <textarea 
                                    placeholder="Description (Optional)"
                                    className="w-full p-2 rounded border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 dark:text-white"
                                    rows={3}
                                    value={newTask.description}
                                    onChange={e => setNewTask({...newTask, description: e.target.value})}
                                />
                                <div className="grid grid-cols-2 gap-3">
                                    <div>
                                        <label className="block text-xs text-slate-500 mb-1">Due Date</label>
                                        <input 
                                            type="date"
                                            required
                                            className="w-full p-2 rounded border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 dark:text-white"
                                            value={newTask.dueDate}
                                            onChange={e => setNewTask({...newTask, dueDate: e.target.value})}
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-xs text-slate-500 mb-1">Priority</label>
                                        <select 
                                            className="w-full p-2 rounded border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 dark:text-white"
                                            value={newTask.priority}
                                            onChange={e => setNewTask({...newTask, priority: e.target.value as TaskPriority})}
                                        >
                                            <option value="low">Low</option>
                                            <option value="medium">Medium</option>
                                            <option value="high">High</option>
                                        </select>
                                    </div>
                                </div>
                                <button type="submit" className="w-full py-2 bg-teal-600 text-white rounded-lg hover:bg-teal-500 font-medium mt-2">
                                    {editingTask ? 'Update Task' : 'Add Task'}
                                </button>
                            </form>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default CalendarView;
