
import React from 'react';

const TermsView: React.FC = () => {
    return (
        <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm p-6 md:p-10 max-w-4xl mx-auto animate-fade-in">
            <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-6">Terms of Service</h1>
            
            <div className="prose dark:prose-invert max-w-none text-slate-600 dark:text-slate-300 space-y-6">
                <p className="text-sm text-slate-500 italic">Last Updated: {new Date().toLocaleDateString()}</p>
                
                <section>
                    <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">1. Acceptance of Terms</h2>
                    <p>
                        By accessing and using SA Bookkeeper AI, you accept and agree to be bound by the terms and provision of this agreement. 
                        In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable 
                        to such services.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">2. Service Description</h2>
                    <p>
                        SA Bookkeeper AI provides automated bookkeeping services using Artificial Intelligence. The services include parsing 
                        PDF bank statements, categorizing transactions, and generating financial reports. 
                    </p>
                    <p className="mt-2 font-semibold text-amber-600 dark:text-amber-400">
                        Disclaimer: The reports and analysis generated by this tool are for informational purposes only and do not constitute 
                        professional financial or tax advice. You should consult with a qualified accountant or tax practitioner for official 
                        SARS submissions.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">3. User Account</h2>
                    <p>
                        You are responsible for maintaining the security of your account and password. SA Bookkeeper AI cannot and will not 
                        be liable for any loss or damage from your failure to comply with this security obligation.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">4. Acceptable Use</h2>
                    <p>
                        You agree not to use the Service to upload, post, host, or transmit unsolicited email, SMSs, or "spam" messages. 
                        You agree not to upload invalid data, viruses, worms, or any code of a destructive nature.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">5. Termination</h2>
                    <p>
                        We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, 
                        including without limitation if you breach the Terms.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">6. Changes to Terms</h2>
                    <p>
                        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material 
                        we will try to provide at least 30 days' notice prior to any new terms taking effect.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-3">7. Governing Law</h2>
                    <p>
                        These Terms shall be governed and construed in accordance with the laws of South Africa, without regard to its conflict 
                        of law provisions.
                    </p>
                </section>
            </div>
        </div>
    );
};

export default TermsView;
